### PR TITLE
refactor to components

### PR DESCRIPTION
**Pull request by askingalot**
It's been a while since I had a chance to work on this, but I finally found myself with a free weekend.

This PR is a pretty drastic change in the code. It's essentially a rewrite. I believe (hope) it will make the code easier to change in the future.

### CODE REVIEW

**Comment by askingalot** [comment]
I forgot to mention @iezer when I originally submitted this. Sorry.

**Comment by iezer** [comment]
@askingalot this looks great. I tried it out locally. I like how the lines disappear when you drag a label on them. Right now if the user gets the answer wrong there is no way to change his/her answer. Do you think it would make sense to make sense to make that possible? We could either reset all the labels, or make them draggable.

**Comment by askingalot** [comment]
I do think it makes sense to let users change their answers. Do you think I should add that ability to this PR?

**Comment by iezer** [comment]
Sorry for the delay. Go ahead and merge this and if you have time make that other change in a subsequent PR.

**Pull request merged**
